In [12]:
a = 10

In [13]:
type(a)

int

In [15]:
first_name = "Megha"
last_name = "Sharma"

In [18]:
print("My first name is {first} and last name is {last}".format(first=first_name,last=last_name))

My first name is Megha and last name is Sharma


In [20]:
lst = [1,1,2,3,4,5,6]
lst

[1, 1, 2, 3, 4, 5, 6]

In [21]:
lst.index(1, 0, 4)

0

In [23]:
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}


In [25]:
set2.intersection(set1)



{'Avengers', 'Hitman', 'IronMan'}

In [27]:
set2.intersection_update(set1)


In [28]:
set2

{'Avengers', 'Hitman', 'IronMan'}

In [29]:
sdset = {}
type(sdset)

dict

In [30]:
set_var= set()
print(set_var)
type(set_var)

set()


set

In [31]:
type(dict())

dict

In [34]:
dict = {"Name":"Megha"}

In [35]:
dict.update({"Profession":"Data Scientist"})

In [36]:
dict

{'Name': 'Megha', 'Profession': 'Data Scientist'}

In [1]:
import numpy as np

In [5]:
arr=np.array([1,4,7,9])

In [39]:
print(arr)

[1 4 7 9]


In [6]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [46]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [47]:
arr[1:3,2:4]

array([[4, 5],
       [6, 8]])

In [49]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [50]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [8]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [1]:
arr=np.arange()

NameError: name 'np' is not defined

In [9]:
arr=np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
arr[3:]=100
arr

array([  1.        ,   1.18367347,   1.36734694, 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        ])

In [12]:
arr[0:]=10
arr

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [13]:
arr[1:]=7
arr

array([10.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,
        7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,
        7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,
        7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.])

In [14]:
arr2 = [2,8,86]

In [15]:
arr2

[2, 8, 86]

In [16]:
type(arr2)

list

In [17]:
arr9 = np.array([6,9,3,84])
arr9

array([ 6,  9,  3, 84])

In [18]:
arr6 = np.array([1,8,4,9])
arr6

array([1, 8, 4, 9])

In [19]:
array9 = arr6

In [20]:
arr9=arr6

In [21]:
arr9

array([1, 8, 4, 9])

In [27]:
type(arr)

numpy.ndarray

In [23]:
np.insert(arr6, 3, 46, axis=None)

array([ 1,  8,  4, 46,  9])

In [24]:
arr9

array([1, 8, 4, 9])

In [32]:
np.insert(arr9, 3, 96, axis=None)

array([ 1,  8,  4, 96,  9])

In [33]:
arr9
arr6

array([1, 8, 4, 9])

In [34]:
arr9

array([1, 8, 4, 9])

In [35]:
arr6

array([1, 8, 4, 9])

In [36]:
arrhj = np.arange(5)

In [39]:
arrhj
arrhj.shape

(5,)

In [40]:
arrhj

array([0, 1, 2, 3, 4])

In [41]:
arrhj = np.arange(12).reshape(3, 4)

In [43]:
arrhj.shape

(3, 4)

In [56]:
arrhj = np.insert(arrhj, 1, 9, axis = 0)

In [57]:
arrhj

array([[ 0,  9,  9,  9,  1,  2,  3],
       [ 9,  9,  9,  9,  9,  9,  9],
       [ 9,  9,  9,  9,  9,  9,  9],
       [ 9,  9,  9,  9,  9,  9,  9],
       [ 4,  9,  9,  9,  5,  6,  7],
       [ 8,  9,  9,  9,  9, 10, 11]])

In [61]:
arryh = np.arange(5)
print("1D arryh : \n", arryh)
print("Shape : ", arryh.shape)
 
# value = 9
# index = 1  
# Insertion before first index
a = np.insert(arryh, 1, 9)
print("\nArray after insertion : ", a)
print("Shape : ", a.shape)
 
 
# Working on 2D array
arryh = np.arange(12).reshape(3, 4)
print("\n\n2D arr : \n", arryh)
print("Shape : ", arryh.shape)
 
a = np.insert(arryh, 1, 9, axis = 0)
print("\nArray after insertion : \n", a)
print("Shape : ", a.shape)

1D arryh : 
 [0 1 2 3 4]
Shape :  (5,)

Array after insertion :  [0 9 1 2 3 4]
Shape :  (6,)


2D arr : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape :  (3, 4)

Array after insertion : 
 [[ 0  1  2  3]
 [ 9  9  9  9]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape :  (4, 4)


In [60]:
val = 2
arr<val


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [62]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
arr_ex=np.random.random_sample(4,4)
arr_ex


array([[-0.14100872,  0.44360107,  0.90501411, -0.13481626],
       [ 0.52270896, -0.5100422 , -0.71086539,  2.02233434],
       [ 1.27239056, -0.6802463 , -0.60830474,  1.85818721],
       [-0.68127724, -1.10926105,  0.60397406,  1.52602132]])

In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row       5'],columns=["Column1","Column2","Column3","Coumn4"])

In [7]:
df.to_csv('Test1')

In [9]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Coumn4     3
Name: Row1, dtype: int32

In [10]:
arr = np.array(df)

In [11]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
type(df)

pandas.core.frame.DataFrame

In [21]:
type(df.iloc[0:1,0])

pandas.core.series.Series

In [22]:
df.iloc[:,1:].shape

(5, 3)

In [23]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Coumn4     0
dtype: int64

In [26]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Coumn4     0
dtype: int64

In [31]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [33]:
type(df)

pandas.core.frame.DataFrame

In [35]:
df[['Column1', 'Column2']]

Column1  Column2
Row1               0        1
Row2               4        5
Row3               8        9
Row4              12       13
Row       5       16       17

In [11]:
df = pd.DataFrame()

In [20]:
df = pd.read_csv('mercedesbenz (1).csv')

In [21]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [23]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [24]:
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [25]:
df[:].value_counts()

ID    y       X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  X12  X13  X14  X15  X16  X17  X18  X19  X20  X21  X22  X23  X24  X26  X27  X28  X29  X30  X31  X32  X33  X34  X35  X36  X37  X38  X39  X40  X41  X42  X43  X44  X45  X46  X47  X48  X49  X50  X51  X52  X53  X54  X55  X56  X57  X58  X59  X60  X61  X62  X63  X64  X65  X66  X67  X68  X69  X70  X71  X73  X74  X75  X76  X77  X78  X79  X80  X81  X82  X83  X84  X85  X86  X87  X88  X89  X90  X91  X92  X93  X94  X95  X96  X97  X98  X99  X100  X101  X102  X103  X104  X105  X106  X107  X108  X109  X110  X111  X112  X113  X114  X115  X116  X117  X118  X119  X120  X122  X123  X124  X125  X126  X127  X128  X129  X130  X131  X132  X133  X134  X135  X136  X137  X138  X139  X140  X141  X142  X143  X144  X145  X146  X147  X148  X150  X151  X152  X153  X154  X155  X156  X157  X158  X159  X160  X161  X162  X163  X164  X165  X166  X167  X168  X169  X170  X171  X172  X173  X174  X175  X176  X177  X178  X179  X180  X181  X182  X183  X184  X185  X186  X187

In [30]:
type(df[df['y']>100])

pandas.core.frame.DataFrame

In [31]:
from io import StringIO, BytesIO
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')


In [32]:
type(data)

str

In [34]:
type(pd.read_csv(StringIO(data)))

pandas.core.frame.DataFrame

In [35]:
## Read from specific columns
df=pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ['COL1', 'COL3'])

In [36]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [41]:
df=pd.read_csv(StringIO(data), usecols=['col1', 'col3'])

In [42]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [43]:
df.to_csv('Test.csv')

In [44]:
df=pd.read_csv(StringIO(data),dtype=object)
df

col1 col2 col3
0    x    y    1
1    a    b    2
2    c    d    3

In [49]:
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11,12')

In [54]:
df=pd.read_csv(StringIO(data),dtype=int)

In [56]:
df['a']

0    1
1    5
2    9
Name: a, dtype: int32

In [57]:
data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')
pd.read_csv(StringIO(data))


a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [65]:
pd.read_csv(StringIO(data), index_col=False)


a       b    c
0  4   apple  bat
1  8  orange  cow

In [71]:
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'
pd.read_csv(StringIO(data),escapechar='\\')


a  b
0  hello, "Bob", nice to see you  5

In [96]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df1=pd.read_json(Data)

In [97]:
type(df1)

pandas.core.frame.DataFrame

In [88]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df.head()


0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [101]:
# convert Json to csv
# convert Json to different json formats
df1.to_json(orient="index")
df1.to_json(orient="records")


'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [104]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
dfs = pd.read_html(url)
dfs

[                         Bank NameBank           CityCity StateSt  CertCert  \
 0                  First Republic Bank      San Francisco      CA     59017   
 1                       Signature Bank           New York      NY     57053   
 2                  Silicon Valley Bank        Santa Clara      CA     24735   
 3                    Almena State Bank             Almena      KS     15426   
 4           First City Bank of Florida  Fort Walton Beach      FL     16748   
 ..                                 ...                ...     ...       ...   
 561                 Superior Bank, FSB           Hinsdale      IL     32646   
 562                Malta National Bank              Malta      OH      6629   
 563    First Alliance Bank & Trust Co.         Manchester      NH     34264   
 564  National State Bank of Metropolis         Metropolis      IL      3815   
 565                   Bank of Honolulu           Honolulu      HI     21029   
 
                  Acquiring Institutio

In [114]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url_mcc, match='Country', header=0)
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [115]:
##Reading Excel Files

In [120]:
df_excel=pd.read_excel('ExcelHistogram.xlsx')
df_excel.head()


Copy data from cell A3 downwards…  Unnamed: 1  Unnamed: 2  Unnamed: 3  \
0                              Data         NaN         NaN         NaN   
1                                 4         NaN         NaN         NaN   
2                                 6         NaN         NaN         NaN   
3                                 7         NaN         NaN         NaN   
4                                 4         NaN         NaN         NaN   

   Unnamed: 4  Unnamed: 5  Unnamed: 6          Unnamed: 7          Unnamed: 8  \
0         NaN         NaN         NaN                 NaN                 NaN   
1         NaN         NaN         NaN                 NaN                 NaN   
2         NaN         NaN  bin decile  bin boundary upper  bin boundary lower   
3         NaN         NaN           0             1.99992                 NaN   
4         NaN         NaN         0.1            2.800008             1.99992   

  Unnamed: 9 Unnamed: 10  
0        NaN         NaN  
1        NaN         NaN  
2      label       count  
3        NaN           0  
4    2 - 2.8           1

In [122]:
#Pickling
df_excel.to_pickle('df_excel')
df=pd.read_pickle('df_excel')
type(df.head())

pandas.core.frame.DataFrame